import { defineConfig } from 'oxlint';

export default defineConfig({
  ignorePatterns: [
    'dist/**',
    'node_modules/**',
    'packages/*/node_modules/**',
    'apps/*/node_modules/**',
  ],
  categories: {
    correctness: 'warn',
  },
  rules: {
    'eslint/eqeqeq': 'error',
    'eslint/max-classes-per-file': ['error', 1],
    'eslint/max-lines': ['error', 400],
    'eslint/no-empty-function': 'warn',
    'eslint/no-restricted-imports': 'warn',
    'eslint/no-shadow': 'warn',
    'eslint/no-unused-expressions': 'off',
    'eslint/no-unused-vars': 'error',
    'eslint/no-useless-concat': 'error',
    'eslint/no-var': 'error',
    'eslint/prefer-const': 'warn',
    'eslint/prefer-destructuring': 'warn',
    'eslint/prefer-spread': 'error',
    'eslint/prefer-template': 'warn',
    // 'eslint/sort-imports': 'error',
    'import/no-absolute-path': 'error',
    'import/unambiguous': 'error',
    'jsdoc/require-param-type': 'warn',
    'jsdoc/require-param': 'warn',
    'promise/prefer-await-to-callbacks': 'warn',
    'promise/prefer-await-to-then': 'warn',
    'typescript/consistent-indexed-object-style': ['error', 'record'],
    'typescript/consistent-type-exports': 'error',
    'typescript/no-explicit-any': 'warn',
    'typescript/no-extraneous-class': 'off',
    'typescript/no-floating-promises': 'warn',
    'typescript/no-import-type-side-effects': 'error',
    'typescript/no-inferable-types': 'error',
    'typescript/no-misused-promises': 'warn',
    'typescript/no-unnecessary-condition': 'error',
    'typescript/no-unnecessary-parameter-property-assignment': 'error',
    'typescript/no-unnecessary-qualifier': 'error',
    'typescript/no-unnecessary-template-expression': 'error',
    'typescript/no-unsafe-argument': 'off',
    'typescript/no-unsafe-assignment': 'off',
    'typescript/no-unsafe-call': 'off',
    'typescript/no-unsafe-member-access': 'off',
    'typescript/no-unsafe-return': 'error',
    'typescript/prefer-as-const': 'warn',
    'typescript/prefer-for-of': 'warn',
    'typescript/prefer-function-type': 'error',
    'typescript/prefer-optional-chain': 'error',
    // 'typescript/prefer-readonly-parameter-types': 'warn',
    // 'typescript/prefer-readonly': 'warn',
    'typescript/promise-function-async': 'error',
    'typescript/require-await': 'error',
    'typescript/restrict-template-expressions': 'error',
    'typescript/return-await': 'error',
    'typescript/unbound-method': 'off',
  },
  settings: {
    jsdoc: {
      ignorePrivate: false,
      ignoreInternal: false,
      ignoreReplacesDocs: true,
      overrideReplacesDocs: true,
      augmentsExtendsReplacesDocs: false,
      implementsReplacesDocs: false,
      exemptDestructuredRootsFromChecks: false,
      tagNamePreference: {},
    },
    vitest: {
      typecheck: false,
    },
  },
  env: {
    builtin: true,
  },
});
